using System.Collections.Generic;
using System.Text;
using ZeroAlloc.Notify.Generator.Models;

namespace ZeroAlloc.Notify.Generator.Writers;

internal static class NotifyWriter
{
    public static string Write(NotifyClassModel model)
    {
        var sb = new StringBuilder();
        WriteFileHeader(sb, model);
        WriteClassOpen(sb, model);
        WriteEventMembers(sb, model);
        WriteFieldMembers(sb, model);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void WriteFileHeader(StringBuilder sb, NotifyClassModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.AsyncEvents;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
    }

    private static void WriteClassOpen(StringBuilder sb, NotifyClassModel model)
    {
        var interfaces = new List<string>();
        if (model.NotifyPropertyChanged)   interfaces.Add("global::ZeroAlloc.AsyncEvents.INotifyPropertyChangedAsync");
        if (model.NotifyPropertyChanging)  interfaces.Add("global::ZeroAlloc.AsyncEvents.INotifyPropertyChangingAsync");
        if (model.NotifyCollectionChanged) interfaces.Add("global::ZeroAlloc.AsyncEvents.INotifyCollectionChangedAsync");
        if (model.NotifyDataErrorInfo)     interfaces.Add("global::ZeroAlloc.AsyncEvents.INotifyDataErrorInfoAsync");

        var interfaceList = interfaces.Count > 0 ? " : " + string.Join(", ", interfaces) : "";
        sb.AppendLine($"partial class {model.TypeName}{interfaceList}");
        sb.AppendLine("{");
    }

    private static void WriteEventMembers(StringBuilder sb, NotifyClassModel model)
    {
        var mode = model.ClassLevelSequential
            ? "global::ZeroAlloc.AsyncEvents.InvokeMode.Sequential"
            : "global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel";

        if (model.NotifyPropertyChanged)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.AsyncEvents.AsyncPropertyChangedEventArgs",
                "_propertyChangedAsync", "PropertyChangedAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangedAsync(string propertyName, global::System.Threading.CancellationToken ct = default)",
                "        => _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.AsyncEvents.AsyncPropertyChangedEventArgs(propertyName), ct);");

        if (model.NotifyPropertyChanging)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.AsyncEvents.AsyncPropertyChangingEventArgs",
                "_propertyChangingAsync", "PropertyChangingAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangingAsync(string propertyName, global::System.Threading.CancellationToken ct = default)",
                "        => _propertyChangingAsync.InvokeAsync(new global::ZeroAlloc.AsyncEvents.AsyncPropertyChangingEventArgs(propertyName), ct);");

        if (model.NotifyCollectionChanged)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.AsyncEvents.AsyncCollectionChangedEventArgs",
                "_collectionChangedAsync", "CollectionChangedAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaiseCollectionChangedAsync(global::ZeroAlloc.AsyncEvents.AsyncCollectionChangedEventArgs args, global::System.Threading.CancellationToken ct = default)",
                "        => _collectionChangedAsync.InvokeAsync(args, ct);");

        if (model.NotifyDataErrorInfo)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.AsyncEvents.AsyncErrorsChangedEventArgs",
                "_errorsChangedAsync", "ErrorsChangedAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaiseErrorsChangedAsync(string? propertyName, global::System.Threading.CancellationToken ct = default)",
                "        => _errorsChangedAsync.InvokeAsync(new global::ZeroAlloc.AsyncEvents.AsyncErrorsChangedEventArgs(propertyName), ct);");
    }

    private static void WriteEventMember(
        StringBuilder sb,
        string mode,
        string argsType,
        string fieldName,
        string eventName,
        string raiseSignature,
        string raiseBody)
    {
        sb.AppendLine($"    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<{argsType}> {fieldName} = new({mode});");
        sb.AppendLine();
        sb.AppendLine("    #pragma warning disable MA0046");
        sb.AppendLine($"    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<{argsType}> {eventName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        add => {fieldName}.Register(value);");
        sb.AppendLine($"        remove => {fieldName}.Unregister(value);");
        sb.AppendLine("    }");
        sb.AppendLine("    #pragma warning restore MA0046");
        sb.AppendLine();
        sb.AppendLine(raiseSignature);
        sb.AppendLine(raiseBody);
        sb.AppendLine();
    }

    private static void WriteFieldMembers(StringBuilder sb, NotifyClassModel model)
    {
        foreach (var field in model.Fields)
            WriteFieldMember(sb, model, field);
    }

    private static void WriteFieldMember(StringBuilder sb, NotifyClassModel model, ObservableFieldModel field)
    {
        sb.AppendLine($"    public {field.TypeName} {field.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {field.FieldName};");
        sb.AppendLine($"        private set => {field.FieldName} = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public async global::System.Threading.Tasks.ValueTask Set{field.PropertyName}Async({field.TypeName} value, global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (global::System.Collections.Generic.EqualityComparer<{field.TypeName}>.Default.Equals({field.FieldName}, value)) return;");
        if (model.NotifyPropertyChanging)
            sb.AppendLine($"        await RaisePropertyChangingAsync(nameof({field.PropertyName}), ct).ConfigureAwait(false);");
        sb.AppendLine($"        {field.FieldName} = value;");
        if (model.NotifyPropertyChanged)
            sb.AppendLine($"        await RaisePropertyChangedAsync(nameof({field.PropertyName}), ct).ConfigureAwait(false);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
