using System.Collections.Generic;
using System.Text;
using ZeroAlloc.Notify.Generator.Models;

namespace ZeroAlloc.Notify.Generator.Writers;

internal static class NotifyWriter
{
    public static string Write(NotifyClassModel model)
    {
        var sb = new StringBuilder();
        WriteFileHeader(sb, model);

        // The containing types, outermost first, then the class itself. A top-level class has
        // no containing types, so its output is written without extra indentation.
        var containing = model.Declarations.Count - 1;
        for (var level = 0; level < containing; level++)
        {
            sb.Append(Indent(level)).AppendLine(model.Declarations[level]);
            sb.Append(Indent(level)).AppendLine("{");
        }

        var body = new StringBuilder();
        WriteClassOpen(body, model);
        WriteEventMembers(body, model);
        WriteFieldMembers(body, model);
        body.AppendLine("}");
        AppendIndented(sb, body.ToString(), Indent(containing));

        for (var level = containing - 1; level >= 0; level--)
            sb.Append(Indent(level)).AppendLine("}");
        return sb.ToString();
    }

    private static string Indent(int level) => new(' ', level * 4);

    /// <summary>Appends <paramref name="text"/> with every non-empty line prefixed by <paramref name="indent"/>.</summary>
    private static void AppendIndented(StringBuilder sb, string text, string indent)
    {
        if (indent.Length == 0)
        {
            sb.Append(text);
            return;
        }

        var start = 0;
        while (start < text.Length)
        {
            var end = text.IndexOf('\n', start);
            var next = end < 0 ? text.Length : end + 1;
            // A blank line stays blank, whether it ends in \n or \r\n.
            var blank = text[start] == '\n' || (text[start] == '\r' && start + 1 < text.Length && text[start + 1] == '\n');
            if (!blank) sb.Append(indent);
            sb.Append(text, start, next - start);
            start = next;
        }
    }

    private static void WriteFileHeader(StringBuilder sb, NotifyClassModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.AsyncEvents;");
        sb.AppendLine("using ZeroAlloc.Notify;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
    }

    private static void WriteClassOpen(StringBuilder sb, NotifyClassModel model)
    {
        var interfaces = new List<string>();
        if (model.NotifyPropertyChanged)   interfaces.Add("global::ZeroAlloc.Notify.INotifyPropertyChangedAsync");
        if (model.NotifyPropertyChanging)  interfaces.Add("global::ZeroAlloc.Notify.INotifyPropertyChangingAsync");
        if (model.NotifyCollectionChanged) interfaces.Add("global::ZeroAlloc.Notify.INotifyCollectionChangedAsync");
        if (model.NotifyDataErrorInfo)     interfaces.Add("global::ZeroAlloc.Notify.INotifyDataErrorInfoAsync");

        var interfaceList = interfaces.Count > 0 ? " : " + string.Join(", ", interfaces) : "";
        sb.AppendLine(model.Declarations[model.Declarations.Count - 1] + interfaceList);
        sb.AppendLine("{");
    }

    private static void WriteEventMembers(StringBuilder sb, NotifyClassModel model)
    {
        var mode = model.ClassLevelSequential
            ? "global::ZeroAlloc.AsyncEvents.InvokeMode.Sequential"
            : "global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel";

        if (model.NotifyPropertyChanged)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs",
                "_propertyChangedAsync", "PropertyChangedAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangedAsync(string propertyName, object? oldValue, object? newValue, global::System.Threading.CancellationToken ct = default)",
                "        => _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs(propertyName, oldValue, newValue), ct);");

        if (model.NotifyPropertyChanging)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs",
                "_propertyChangingAsync", "PropertyChangingAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangingAsync(string propertyName, object? oldValue, object? newValue, global::System.Threading.CancellationToken ct = default)",
                "        => _propertyChangingAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs(propertyName, oldValue, newValue), ct);");

        if (model.NotifyCollectionChanged)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.Notify.AsyncCollectionChangedEventArgs",
                "_collectionChangedAsync", "CollectionChangedAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaiseCollectionChangedAsync(global::ZeroAlloc.Notify.AsyncCollectionChangedEventArgs args, global::System.Threading.CancellationToken ct = default)",
                "        => _collectionChangedAsync.InvokeAsync(args, ct);");

        if (model.NotifyDataErrorInfo)
            WriteEventMember(sb, mode,
                "global::ZeroAlloc.Notify.AsyncErrorsChangedEventArgs",
                "_errorsChangedAsync", "ErrorsChangedAsync",
                "    protected global::System.Threading.Tasks.ValueTask RaiseErrorsChangedAsync(string? propertyName, global::System.Threading.CancellationToken ct = default)",
                "        => _errorsChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncErrorsChangedEventArgs(propertyName), ct);");
    }

    private static void WriteEventMember(
        StringBuilder sb,
        string mode,
        string argsType,
        string fieldName,
        string eventName,
        string raiseSignature,
        string raiseBody)
    {
        sb.AppendLine($"    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<{argsType}> {fieldName} = new({mode});");
        sb.AppendLine();
        sb.AppendLine("    #pragma warning disable MA0046");
        sb.AppendLine($"    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<{argsType}> {eventName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        add => {fieldName}.Register(value);");
        sb.AppendLine($"        remove => {fieldName}.Unregister(value);");
        sb.AppendLine("    }");
        sb.AppendLine("    #pragma warning restore MA0046");
        sb.AppendLine();
        sb.AppendLine(raiseSignature);
        sb.AppendLine(raiseBody);
        sb.AppendLine();
    }

    private static void WriteFieldMembers(StringBuilder sb, NotifyClassModel model)
    {
        foreach (var field in model.Fields)
            WriteFieldMember(sb, model, field);
    }

    private static void WriteFieldMember(StringBuilder sb, NotifyClassModel model, ObservableFieldModel field)
    {
        sb.AppendLine($"    public {field.TypeName} {field.PropertyName}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => {field.FieldName};");
        sb.AppendLine($"        private set => {field.FieldName} = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public async global::System.Threading.Tasks.ValueTask Set{field.PropertyName}Async({field.TypeName} value, global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (global::System.Collections.Generic.EqualityComparer<{field.TypeName}>.Default.Equals({field.FieldName}, value)) return;");
        sb.AppendLine($"        var __old = {field.FieldName};");
        if (model.NotifyPropertyChanging)
        {
            if (field.Sequential && !model.ClassLevelSequential)
                sb.AppendLine($"        await _propertyChangingAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs(nameof({field.PropertyName}), __old, value), global::ZeroAlloc.AsyncEvents.InvokeMode.Sequential, ct).ConfigureAwait(false);");
            else
                sb.AppendLine($"        await RaisePropertyChangingAsync(nameof({field.PropertyName}), __old, value, ct).ConfigureAwait(false);");
        }
        sb.AppendLine($"        {field.FieldName} = value;");
        if (model.NotifyPropertyChanged)
        {
            if (field.Sequential && !model.ClassLevelSequential)
                sb.AppendLine($"        await _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs(nameof({field.PropertyName}), __old, value), global::ZeroAlloc.AsyncEvents.InvokeMode.Sequential, ct).ConfigureAwait(false);");
            else
                sb.AppendLine($"        await RaisePropertyChangedAsync(nameof({field.PropertyName}), __old, value, ct).ConfigureAwait(false);");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
