//HintName: MyCollection.Notify.g.cs
// <auto-generated/>
#nullable enable

using System.Collections;
using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.AsyncEvents;
using ZeroAlloc.Notify;

partial class MyCollection : global::ZeroAlloc.Notify.INotifyCollectionChangedAsync
{
    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.Notify.AsyncCollectionChangedEventArgs> _collectionChangedAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel);

    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.Notify.AsyncCollectionChangedEventArgs> CollectionChangedAsync
    {
        add => _collectionChangedAsync.Register(value);
        remove => _collectionChangedAsync.Unregister(value);
    }
    #pragma warning restore MA0046

    protected global::System.Threading.Tasks.ValueTask RaiseCollectionChangedAsync(global::ZeroAlloc.Notify.AsyncCollectionChangedEventArgs args, global::System.Threading.CancellationToken ct = default)
        => _collectionChangedAsync.InvokeAsync(args, ct);

}
