//HintName: MyModel.Notify.g.cs
// <auto-generated/>
#nullable enable

using System.Collections;
using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.AsyncEvents;
using ZeroAlloc.Notify;

partial class MyModel : global::ZeroAlloc.Notify.INotifyDataErrorInfoAsync
{
    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.Notify.AsyncErrorsChangedEventArgs> _errorsChangedAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel);

    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.Notify.AsyncErrorsChangedEventArgs> ErrorsChangedAsync
    {
        add => _errorsChangedAsync.Register(value);
        remove => _errorsChangedAsync.Unregister(value);
    }
    #pragma warning restore MA0046

    protected global::System.Threading.Tasks.ValueTask RaiseErrorsChangedAsync(string? propertyName, global::System.Threading.CancellationToken ct = default)
        => _errorsChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncErrorsChangedEventArgs(propertyName), ct);

}
