//HintName: MyViewModel.Notify.g.cs
// <auto-generated/>
#nullable enable

using System.Collections;
using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.AsyncEvents;

partial class MyViewModel : global::ZeroAlloc.AsyncEvents.INotifyPropertyChangedAsync
{
    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.AsyncEvents.AsyncPropertyChangedEventArgs> _propertyChangedAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel);

    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.AsyncEvents.AsyncPropertyChangedEventArgs> PropertyChangedAsync
    {
        add => _propertyChangedAsync.Register(value);
        remove => _propertyChangedAsync.Unregister(value);
    }
    #pragma warning restore MA0046

    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangedAsync(string propertyName, global::System.Threading.CancellationToken ct = default)
        => _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.AsyncEvents.AsyncPropertyChangedEventArgs(propertyName), ct);

}
