//HintName: MyViewModel.Notify.g.cs
// <auto-generated/>
#nullable enable

using System.Collections;
using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.AsyncEvents;
using ZeroAlloc.Notify;

partial class MyViewModel : global::ZeroAlloc.Notify.INotifyPropertyChangedAsync, global::ZeroAlloc.Notify.INotifyPropertyChangingAsync
{
    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs> _propertyChangedAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel);

    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs> PropertyChangedAsync
    {
        add => _propertyChangedAsync.Register(value);
        remove => _propertyChangedAsync.Unregister(value);
    }
    #pragma warning restore MA0046

    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangedAsync(string propertyName, object? oldValue, object? newValue, global::System.Threading.CancellationToken ct = default)
        => _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs(propertyName, oldValue, newValue), ct);

    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs> _propertyChangingAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel);

    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs> PropertyChangingAsync
    {
        add => _propertyChangingAsync.Register(value);
        remove => _propertyChangingAsync.Unregister(value);
    }
    #pragma warning restore MA0046

    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangingAsync(string propertyName, object? oldValue, object? newValue, global::System.Threading.CancellationToken ct = default)
        => _propertyChangingAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs(propertyName, oldValue, newValue), ct);

    public string Name
    {
        get => _name;
        private set => _name = value;
    }

    public async global::System.Threading.Tasks.ValueTask SetNameAsync(string value, global::System.Threading.CancellationToken ct = default)
    {
        if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_name, value)) return;
        var __old = _name;
        await RaisePropertyChangingAsync(nameof(Name), __old, value, ct).ConfigureAwait(false);
        _name = value;
        await RaisePropertyChangedAsync(nameof(Name), __old, value, ct).ConfigureAwait(false);
    }

    public int Count
    {
        get => _count;
        private set => _count = value;
    }

    public async global::System.Threading.Tasks.ValueTask SetCountAsync(int value, global::System.Threading.CancellationToken ct = default)
    {
        if (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_count, value)) return;
        var __old = _count;
        await RaisePropertyChangingAsync(nameof(Count), __old, value, ct).ConfigureAwait(false);
        _count = value;
        await RaisePropertyChangedAsync(nameof(Count), __old, value, ct).ConfigureAwait(false);
    }

}
