//HintName: MyApp.Orders`1+Views+OrderViewModel`1.Notify.g.cs
// <auto-generated/>
#nullable enable

using System.Collections;
using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.AsyncEvents;
using ZeroAlloc.Notify;

namespace MyApp;

partial record struct Orders<TKey>
{
    partial class Views
    {
        partial class OrderViewModel<@event> : global::ZeroAlloc.Notify.INotifyPropertyChangedAsync, global::ZeroAlloc.Notify.INotifyPropertyChangingAsync
        {
            private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs> _propertyChangedAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel);

            #pragma warning disable MA0046
            public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs> PropertyChangedAsync
            {
                add => _propertyChangedAsync.Register(value);
                remove => _propertyChangedAsync.Unregister(value);
            }
            #pragma warning restore MA0046

            protected global::System.Threading.Tasks.ValueTask RaisePropertyChangedAsync(string propertyName, object? oldValue, object? newValue, global::System.Threading.CancellationToken ct = default)
                => _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs(propertyName, oldValue, newValue), ct);

            private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs> _propertyChangingAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Parallel);

            #pragma warning disable MA0046
            public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs> PropertyChangingAsync
            {
                add => _propertyChangingAsync.Register(value);
                remove => _propertyChangingAsync.Unregister(value);
            }
            #pragma warning restore MA0046

            protected global::System.Threading.Tasks.ValueTask RaisePropertyChangingAsync(string propertyName, object? oldValue, object? newValue, global::System.Threading.CancellationToken ct = default)
                => _propertyChangingAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs(propertyName, oldValue, newValue), ct);

            public TKey? Id
            {
                get => _id;
                private set => _id = value;
            }

            public async global::System.Threading.Tasks.ValueTask SetIdAsync(TKey? value, global::System.Threading.CancellationToken ct = default)
            {
                if (global::System.Collections.Generic.EqualityComparer<TKey?>.Default.Equals(_id, value)) return;
                var __old = _id;
                await RaisePropertyChangingAsync(nameof(Id), __old, value, ct).ConfigureAwait(false);
                _id = value;
                await RaisePropertyChangedAsync(nameof(Id), __old, value, ct).ConfigureAwait(false);
            }

            public @event? Payload
            {
                get => _payload;
                private set => _payload = value;
            }

            public async global::System.Threading.Tasks.ValueTask SetPayloadAsync(@event? value, global::System.Threading.CancellationToken ct = default)
            {
                if (global::System.Collections.Generic.EqualityComparer<@event?>.Default.Equals(_payload, value)) return;
                var __old = _payload;
                await _propertyChangingAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangingEventArgs(nameof(Payload), __old, value), global::ZeroAlloc.AsyncEvents.InvokeMode.Sequential, ct).ConfigureAwait(false);
                _payload = value;
                await _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs(nameof(Payload), __old, value), global::ZeroAlloc.AsyncEvents.InvokeMode.Sequential, ct).ConfigureAwait(false);
            }

        }
    }
}
