//HintName: MyViewModel.Notify.g.cs
// <auto-generated/>
#nullable enable

using System.Collections;
using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.AsyncEvents;
using ZeroAlloc.Notify;

partial class MyViewModel : global::ZeroAlloc.Notify.INotifyPropertyChangedAsync
{
    private global::ZeroAlloc.AsyncEvents.AsyncEventHandler<global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs> _propertyChangedAsync = new(global::ZeroAlloc.AsyncEvents.InvokeMode.Sequential);

    #pragma warning disable MA0046
    public event global::ZeroAlloc.AsyncEvents.AsyncEvent<global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs> PropertyChangedAsync
    {
        add => _propertyChangedAsync.Register(value);
        remove => _propertyChangedAsync.Unregister(value);
    }
    #pragma warning restore MA0046

    protected global::System.Threading.Tasks.ValueTask RaisePropertyChangedAsync(string propertyName, object? oldValue, object? newValue, global::System.Threading.CancellationToken ct = default)
        => _propertyChangedAsync.InvokeAsync(new global::ZeroAlloc.Notify.AsyncPropertyChangedEventArgs(propertyName, oldValue, newValue), ct);

    public string Name
    {
        get => _name;
        private set => _name = value;
    }

    public async global::System.Threading.Tasks.ValueTask SetNameAsync(string value, global::System.Threading.CancellationToken ct = default)
    {
        if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_name, value)) return;
        var __old = _name;
        _name = value;
        await RaisePropertyChangedAsync(nameof(Name), __old, value, ct).ConfigureAwait(false);
    }

}
